version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/oleg/.ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - OLLAMA_MODE=cpu

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5679
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_COOKIE_SECURITY=none
      - WEBHOOK_URL=http://localhost:5679/
      - GENERIC_TIMEZONE=Europe/Moscow
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=mydatabase
      - DB_POSTGRESDB_USER=myuser
      - DB_POSTGRESDB_PASSWORD=mypassword
      - N8N_ALLOWED_FILE_SYSTEM_PATHS=/home/node/.n8n
    volumes:
      - /Users/oleg/n8n-data:/home/node/.n8n
      - /Users/oleg/pdf-upload:/tmp/files  # ← добавили том
    restart: unless-stopped
    networks:
      - app-network

  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama-data:
  n8n-data:
  postgresql_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge